

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 20, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(224, 27, 36);\n"
"")
        self.label_2.setLineWidth(4)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 130, 231, 151))
        self.label_3.setStyleSheet("border-image: url(:/pic/motel.png)")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.btn_Cashier = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Cashier.setGeometry(QtCore.QRect(430, 130, 101, 151))
        self.btn_Cashier.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_Cashier.setText("")
        self.btn_Cashier.setObjectName("btn_Cashier")
        self.btn_Inven = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Inven.setGeometry(QtCore.QRect(430, 300, 101, 151))
        self.btn_Inven.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_Inven.setText("")
        self.btn_Inven.setObjectName("btn_Inven")
        self.btn_Employ = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Employ.setGeometry(QtCore.QRect(590, 130, 101, 151))
        self.btn_Employ.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_Employ.setText("")
        self.btn_Employ.setObjectName("btn_Employ")
        self.btn_Consum = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Consum.setGeometry(QtCore.QRect(100, 300, 101, 151))
        self.btn_Consum.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_Consum.setText("")
        self.btn_Consum.setObjectName("btn_Consum")
        self.btn_Static = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Static.setGeometry(QtCore.QRect(260, 300, 101, 151))
        self.btn_Static.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_Static.setText("")
        self.btn_Static.setObjectName("btn_Static")
        self.btn_Logout = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Logout.setGeometry(QtCore.QRect(590, 300, 101, 151))
        self.btn_Logout.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_Logout.setText("")
        self.btn_Logout.setObjectName("btn_Logout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(440, 140, 71, 71))
        self.label_4.setStyleSheet("border-image: url(:/pic/electricity-bill.png)")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(440, 240, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(450, 320, 61, 71))
        self.label_6.setStyleSheet("border-image: url(:/pic/accommodation.png)")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(450, 420, 71, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(610, 150, 67, 71))
        self.label_8.setStyleSheet("border-image: url(:/pic/check-in.png)")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(620, 250, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(120, 320, 67, 61))
        self.label_10.setStyleSheet("border-image: url(:/pic/face.png)")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(110, 410, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(280, 320, 71, 71))
        self.label_12.setStyleSheet("border-image: url(:/pic/faucet.png)")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(270, 410, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(610, 330, 67, 61))
        self.label_18.setStyleSheet("border-image: url(:/pic/logout.png)")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(610, 420, 61, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.label_20.setStyleSheet("border-image: url(image-Ui/background.jpg);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_20.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.btn_Cashier.raise_()
        self.btn_Inven.raise_()
        self.btn_Employ.raise_()
        self.btn_Consum.raise_()
        self.btn_Static.raise_()
        self.btn_Logout.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Motel Manager"))
        self.label_5.setText(_translate("MainWindow", "Electric Bill"))
        self.label_7.setText(_translate("MainWindow", "Rooms"))
        self.label_9.setText(_translate("MainWindow", "Guest"))
        self.label_11.setText(_translate("MainWindow", "Face \n"
"recognition"))
        self.label_13.setText(_translate("MainWindow", "Water Bill"))
        self.label_19.setText(_translate("MainWindow", "Log Out"))
import Home_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
